source 'https://rubygems.org'

puppetversion = ENV.key?('PUPPET_VERSION') ? "= #{ENV['PUPPET_VERSION']}" : ['>= 3.3']
gem 'puppet', '3.8.7'
gem 'puppetlabs_spec_helper', '>= 0.1.0'
gem 'puppet-lint', '>= 0.3.2'
gem 'facter', '>= 1.7.0'
  gem 'metadata-json-lint'
  gem 'rspec-puppet-facts'
  gem 'rubocop', '0.43'
  gem 'puppet-strings'
  gem 'rspec-puppet'
  gem 'rspec-puppet-utils'
  gem 'simplecov', '>= 0.11.0'
  gem 'simplecov-console'
